language: php

php:
  - 7.0
  - 7.1

install:
  - composer clear-cache
  - composer config github-oauth.github.com ${GITHUB_TOKEN};
  - composer global require fxp/composer-asset-plugin
  - composer install --no-interaction --prefer-dist

script: vendor/bin/phpunit

after_success:
  - travis_retry php vendor/bin/coveralls -v

cache:
  directories:
  - vendor
  - $HOME/.cache/composer